### PR TITLE
run specs against postgresql 9.4

### PR DESCRIPTION
**Pull request by BM5k**
I’ve also upgraded our staging database from 9.3.4 to 9.4.0. If everybody’s happy, we can move from 9.3.5 to 9.4.0 in production, too

## ci
- [x] update travis

### CODE REVIEW

**Comment by BM5k** [comment]
Example of how to do this :hankey: via the heroku CLI:

```
# add or update the pg transfer plugin as needed
heroku plugins:install https://github.com/ddollar/heroku-pg-transfer
heroku plugins:update

# back up the existing database
heroku pg:backups capture --expire

# provision the new db
heroku addons:add heroku-postgresql:DB_TYPE --version=9.4 --remote staging

# transfer data
heroku pg:transfer --from DATABASE_URL --to HEROKU_POSTGRESQL_<color>_URL --remote staging

# promote new db
heroku pg:promote HEROKU_POSTGRESQL_<color>_URL --remote staging

# restart the app
heroku ps:restart —remote staging

# remove old database
# make sure you have the correct db name or you’ll remove the db you just added!
heroku addons:remove HEROKU_POSTGRESQL_<color>_URL 
```

Notes:
- staging uses `hobby-dev`
- production uses `hobby-basic`
- the HEROKU_POSTGRESQL_<color>_URL is randomly generated when the db is provisioned

**Comment by mtchavez** [comment]
:+1: for this. The VM has 9.4 if we get around to using that.

**Comment by BM5k** [comment]
I don’t see any reason _not_ to merge this.

**Comment by BM5k** [comment]
If we want, we can move the un-finished steps out into their own issue.

**Comment by mtchavez** [comment]
That's a good approach. Separate issues for migrating to 9.4 for staging and production

**Comment by mtchavez** [comment]
Once those are created I can merge this.

**Comment by BM5k** [comment]
:clap:

**Pull request merged**
