### PR TITLE
add rubocop

### PR DESCRIPTION
**Pull request by BM5k**
I imported the Dev Fu! config, but none of these are set in stone. I figured this is a good start. We should be open to any changes that increase readability or maintainability.

### CODE REVIEW

**Comment by BM5k** [comment]
Grr, not happy with some of the whitespace changes, which aren’t present in the project I pulled this config from, so it looks like I screwed something up.

**Comment by BM5k** [comment]
Should be g2g :meow:

**Comment by bowerman** [comment]
I like rubocop, and I like 99.9% of settings. Should we be enforcing this on a project level vs having a style guide and supplying the rubocop for suggested use?

**Comment by mtchavez** [comment]
If it isn't enforced for the project then who would follow it and what would be the point right?

**Comment by mtchavez** [comment]
:+1:

**Comment by bowerman** [comment]
I don't mind, just saying It might keep people from wanting to contribute.

**Comment by mtchavez** [comment]
Guess we'll see if it ever gets to that point.

**Comment by BM5k** [comment]
@meeples/owners about enforcement: running `rake spec` invokes rubocop with the `-aD` flag, which will automagically fix many things, and provide a detailed-ish report of things that it doesn’t like.

Running the specs and making sure the build passes _should_ be part of contributing to OSS, right?

**Comment by bowerman** [comment]
If it fixes them so be it. but I am NOT in favor of breaking the build for style enforcement.

**Comment by BM5k** [comment]
I’m in favor of breaking the build to enforce style. What about you, @mtchavez?

**Comment by BM5k** [comment]
@bowerman if something style-related breaks the build we can always discuss changing or disabling that rule.

**Pull request merged**
