### PR TITLE
use rack canonical host middleware to set hostname via env var

### PR DESCRIPTION
**Pull request by BM5k**
[re #65]

### CODE REVIEW

**Comment by BM5k** [comment]
this is based on #67

**Comment by mtchavez** [comment]
What are we going to set the `CANONICAL_HOST` to on production? We will use this to use a non meepl.es domain?

**Comment by BM5k** [comment]
@mtchavez yeah, in production (for now) we can set it to meeples.herokuapp.com; when we get a new domain (or get meepl.es unbanned from facebook) we can switch it again.

**Comment by mtchavez** [comment]
OK, let's do that so we can merge this and deploy without issue.

**Comment by mtchavez** [comment]
:+1:  looks good

**Comment by BM5k** [comment]
Done; it’s also set to the proper value on staging

**Pull request merged**
