### PR TITLE
hide footer on small devices

### PR DESCRIPTION
**Pull request by BM5k**

### CODE REVIEW

**Comment by BM5k** [comment]
rebased

**Comment by bowerman** [comment]
no auto heroku app?

**Comment by bowerman** [comment]
did you mean to have the footer NOT displayed on `lg` and `sm`?

You probably want `.hidden-xs` instead, yes?

**Comment by BM5k** [comment]
Oh :crap:, that’s why it was `.visible-md.visible-lg` before. It’s either that or `.hidden-xs.hidden-sm`

**Comment by bowerman** [comment]
sixty-one, half a :chicken: the other

**Pull request merged**
