### PR TITLE
add rspec-retry to re-run stupid test failures on ci

### PR DESCRIPTION
**Pull request by BM5k**

### CODE REVIEW

**Comment by bowerman** [comment]
this still wanted?

**Comment by BM5k** [comment]
@bowerman ¯\(°_o)/¯ couldn’t hurt?

**Comment by BM5k** [comment]
The intermittent spec failures that this was attempting to work around seem to have been fixed.

**Comment by BM5k** [comment]
There doesn’t seem to be a need for this anymore. Unless anyone objects, I’m going to delete the branch.

**Pull request closed without merging**
