### PR TITLE
Vagrantfile added

### LINKED ISSUE #72: Vagrant Setup
Initial Requirements:

- [x] Ubuntu 14.04 LTS
- [x] RVM with Ruby 2.2.0 and bundler
- [x] ~~Unicorn serving the app~~ (handled by bundler no provisioning needed)
- [x] Redis 2.8.19
- [x] Postgres 9.4
- [x] Phantomjs for headless browser testing
- [x] Nodejs 0.12.0 for coffeescript and assets and JS engine
- [x] Memcached 1.4.22 just in case (being used in prod)

### PR DESCRIPTION
**Pull request by mtchavez**
Vagrant setup to fix #72 

## Pre-requisites

* Virtualbox `>= 4.3.20`
* Vagrant `>= 1.7.2`

## Using

* After you have set up Virutalbox and Vagrant you should just need to do `vagrant up`
* Use `vagrant ssh` to get into the VM, which will put you into the app directory
* The box has RVM and bundler so installing dependencies should be the same
* Run app with `bundle exec foreman start` and visit on host `192.168.33.10:5000`

## Gotchas

* We are using NFS which may ask you to enter your sudo password on the host box
* If it asks you for the `vagrant` user password this is `vagrant`

### CODE REVIEW

**Comment by BM5k** [comment]
I assume that `box 'mtchavez/rails-dev’` is open source and not proprietary?

**Comment by mtchavez** [comment]
Si señor

**Comment by BM5k** [comment]
This is pretty much stuck until mitchellh/vagrant#5186 gets resolved.

**Comment by mtchavez** [comment]
Re-opening:

If you already tried this out and added the box then please update:

`vagrant box update --box mtchavez/rails-dev --provider virtualbox`

Let me know if it still doesn't work.

**Comment by BM5k** [comment]
@mtchavez:

```
vagrant@meeples-dev:/srv/app$ bundle
The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'
```

I was able to `gem install bundler`

**Comment by BM5k** [comment]
Also, still having to double exit:

```
vagrant@meeples-dev:/srv/app$ exit
logout
vagrant@meeples-dev:~$ exit
logout
Connection to 127.0.0.1 closed.
```

**Comment by BM5k** [comment]
After exiting, I have some untracked files in my working dir:

```
On branch vagrant
Your branch is up-to-date with 'origin/vagrant'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.vagrant/
```

Should this be added to the .gitignore, or is this supposed to be in my global gitignore?

**Comment by mtchavez** [comment]
* That's odd bundler wasn't found, might be an issue.
* Double exit is expect
* Yes you should be globally ignoring vagrant artifacts like `.vagrant` and `*.box`

**Comment by BM5k** [comment]
- the bundler thing is minor
- oh
- fixed

**Comment by BM5k** [comment]
@mtchavez: want to rebase against master and see if our CI failures go away?

**Comment by mtchavez** [comment]
What's the status on this. Anything to change or update?

**Comment by BM5k** [comment]
@mtchavez I wasn't sure if you wanted to mess with the bundler issue. I guess that could be tackled in a separate PR.

**Pull request merged**
